### ISSUE TITLE
二维码扫码打开崩溃 android6.0 OPPO R9

### ISSUE THREAD

**Issue by hibari9** [vondear/RxTools#15]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yusi.scloud-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yusi.scloud-1/lib/arm64, /data/app/com.yusi.scloud-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libzbar.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:1076)
	at com.zbar.lib.ZbarManager.<clinit>(ZbarManager.java:10)
	at com.vondear.rxtools.model.scaner.DecodeHandler.decode(DecodeHandler.java:44)
	at com.vondear.rxtools.model.scaner.DecodeHandler.handleMessage(DecodeHandler.java:26)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at com.vondear.rxtools.model.scaner.DecodeThread.run(DecodeThread.java:40)

**Comment by Jacky-Xu** [comment]
@hibari9   你解决了吗？

**Comment by JsonZhangCZ** [comment]
这个是少so包造成的

**Comment by Jacky-Xu** [comment]
@JsonZhangCZ  应该是少了arm8平台的so文件
