### ISSUE TITLE
libzbar.so is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by hcw2175** [vondear/RxTools#30]
你好：
      我使用你的库，然后把jniLibs文件拷贝到项目中，但提示找不到’arm64-v8a/libzbar.so‘，然后就创建`arm64-v8a`，并从其它文件夹拷贝2个so文件过来，提示错误：

```
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/io.iotp.app.debug-1/lib/arm64/libzbar.so" is 32-bit instead of 64-bit
                                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:994)
                                                                       at java.lang.System.loadLibrary(System.java:1533)
                                                                       at com.zbar.lib.ZbarManager.<clinit>(ZbarManager.java:12)
```

将其它文件夹的拷贝粘贴过来试过，都不行，不知道该怎么解决！

**Comment by UltramanTIGA** [comment]
遇到同样的问题，找了半天没找到arm64的libzbar.so，希望作者帮忙

**Comment by hcw2175** [comment]
@UltramanTIGA 我在app的bulid.gradle文件中添加以下配置解决了：

```
defaultConfig {
       ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi', 'x86'//, 'armeabi-v7a', 'x86_64', 'arm64-v8a'
        }
}
```
希望能帮到你。
