### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by memedahui** [vondear/RxTools#4]
1，public void onTabChildClick(int position, ImageView currentImageIcon, TextView currentTextView) {
                **RxToast.showToast(position);**
            }
Toast里面不能是int，否则报错
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.wisdom.administrator, PID: 30461
                  android.content.res.Resources$NotFoundException: String resource ID #0x1
                      at android.content.res.Resources.getText(Resources.java:342)
                      at android.content.res.Resources.getString(Resources.java:440)
                      at android.content.Context.getString(Context.java:399)
                      at com.vondear.rxtools.view.RxToast.showToast(RxToast.java:384)
                      at com.wisdom.administrator.activity.MainActivity$1$override.onTabChildClick(MainActivity.java:62)
                      at com.wisdom.administrator.activity.MainActivity$1$override.access$dispatch(MainActivity.java)
                      at com.wisdom.administrator.activity.MainActivity$1.onTabChildClick(MainActivity.java:0)
                      at com.ycl.tabview.library.TabView$1.onClick(TabView.java:270)
                      at android.view.View.performClick(View.java:4909)
                      at android.view.View$PerformClick.run(View.java:20390)
                      at android.os.Handler.handleCallback(Handler.java:815)
                      at android.os.Handler.dispatchMessage(Handler.java:104)
                      at android.os.Looper.loop(Looper.java:192)
                      at android.app.ActivityThread.main(ActivityThread.java:5886)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1031)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
2，包的依赖很多怎么办，应为我发现你应用了支付宝和微信的sdk。这样我就不能用第三方集成登录了，应为build apk失败。。。

**Comment by vondear** [comment]
1，因为我是使用的 字符串 与 字符串的资源引用 [ int ]（例如：R.String.app_name）作为Toast的参数。
2，可以试下这样设置
          compile('com.github.vondear:RxTools:v1.6.8') {
                     exclude group: 'com.tencent.mm.opensdk'
                     exclude group: 'com.alipay.sdk'
          }
